# core/chapters_data.py

SYLLABUS = {
    'sslc': {
        'physics': [
            {'id': 1, 'name': 'Sound Waves',
                'file_url': '/media/sslc/phy/phy_ch1.pdf'},
            {'id': 2, 'name': 'Lenses',
                'file_url': '/media/sslc/phy/ch2.pdf'},
            {'id': 3, 'name': 'Worls of Colours and Vision',
                'file_url': '/media/sslc/phy/ch3.pdf'},
            {'id': 4, 'name': 'Magnetic Effects of Electric Current',
                'file_url': '/media/sslc/phy/ch4.pdf'},
            {'id': 5, 'name': 'Electric Energy: Consuption and Conservation ',
                'file_url': '/media/sslc/phy/ch5.pdf'},
            {'id': 6, 'name': 'Electromagnetic Induction in Daily Life',
                'file_url': '/media/sslc/phy/ch6.pdf'},
            {'id': 7, 'name': 'Mechanical Advantage in Actions',
                'file_url': '/media/sslc/phy/ch7.pdf'},
        ],
        'it': [
            {'id': 1, 'name': 'Design Your Own Posters (GIMP)',
                'file_url': '/media/sslc/it/ch1.pdf'},
            {'id': 2, 'name': 'Publishing (Inkscape/LibreOffice)',
                'file_url': '/media/sslc/it/ch2.pdf'},
            {'id': 3, 'name': 'Attractive Web Designing (HTML)',
                'file_url': '/media/sslc/it/ch3.pdf'},
            {'id': 4, 'name': 'Python Graphics (Turtle)',
                'file_url': '/media/sslc/it/ch4.pdf'},
            {'id': 5, 'name': 'Database Introduction (LibreOffice Base)',
                'file_url': '/media/sslc/it/ch5.pdf'},
            {'id': 6, 'name': 'Information Reading (Computer Hardware)',
                'file_url': '/media/sslc/it/ch6.pdf'},
            {'id': 7, 'name': 'Video Editing (Kdenlive)',
                'file_url': '/media/sslc/it/ch7.pdf'},
            {'id': 8, 'name': 'Computer Network',
                'file_url': '/media/sslc/it/ch8.pdf'},
            {'id': 9, 'name': 'Services in Internet',
                'file_url': '/media/sslc/it/ch9.pdf'},
            {'id': 10, 'name': 'Malayalam Computing',
                'file_url': '/media/sslc/it/ch10.pdf'},
        ],
        'chemistry': [
            {'id': 1, 'name': 'Nomenclature of Organic Compounds and Isomerism',
                'file_url': '/media/sslc/chem/ch1.pdf'},
            {'id': 2, 'name': 'Chemical Reactions of Organic Compounds',
                'file_url': '/media/sslc/chem/ch2.pdf'},
            {'id': 3, 'name': 'Periodic Table and Electronic Configuration',
                'file_url': '/media/sslc/chem/ch3.pdf'},
            {'id': 4, 'name': 'Gas Laws and Mole Concept',
                'file_url': '/media/sslc/chem/ch4.pdf'},
            {'id': 5, 'name': 'Electrochemistry',
                'file_url': '/media/sslc/chem/ch5.pdf'},
            {'id': 6, 'name': 'Metals',
                'file_url': '/media/sslc/chem/ch6.pdf'},
            {'id': 7, 'name': 'Some Compounds of Industrail Importance',
                'file_url': '/media/sslc/chem/ch7.pdf'},
        ],
        'biology': [
            {'id': 1, 'name': 'Genetics of Life',
                'file_url': '/media/sslc/bio/ch1.pdf'},
            {'id': 2, 'name': 'Paths of Evolution',
                'file_url': '/media/sslc/bio/ch2.pdf'},
            {'id': 3, 'name': 'Behind Sensations',
                'file_url': '/media/sslc/bio/ch3.pdf'},
            {'id': 4, 'name': 'Chemoreception in Organisms',
                'file_url': '/media/sslc/bio/ch4.pdf'},
            {'id': 5, 'name': 'Immunity and Healthcare',
                'file_url': '/media/sslc/bio/ch5.pdf'},
            {'id': 6, 'name': 'Biology and Technology',
                'file_url': '/media/sslc/bio/ch6.pdf'},
        ],
        'mathematics': [
            {'id': 1, 'name': 'Arithmetic Sequences',
                'file_url': '/media/sslc/math/ch1.pdf'},
            {'id': 2, 'name': 'Circles',
                'file_url': '/media/sslc/math/ch2.pdf'},
            {'id': 3, 'name': 'Mathematics of Chance',
                'file_url': '/media/sslc/math/ch3.pdf'},
            {'id': 4, 'name': 'Second Degree Equations',
                'file_url': '/media/sslc/math/ch4.pdf'},
            {'id': 5, 'name': 'Trigonometry',
                'file_url': '/media/sslc/math/ch5.pdf'},
            {'id': 6, 'name': 'Coordinates',
             'file_url': '/media/sslc/math/ch6.pdf'},
            {'id': 7, 'name': 'Tangents',
             'file_url': '/media/sslc/math/ch7.pdf'},
            {'id': 8, 'name': 'Solids',
             'file_url': '/media/sslc/math/ch8.pdf'},
            {'id': 9, 'name': 'Geometry and Algebra',
                'file_url': '/media/sslc/math/ch9.pdf'},
            {'id': 10, 'name': 'Polynomials',
                'file_url': '/media/sslc/math/ch10.pdf'},
            {'id': 11, 'name': 'Statistics',
             'file_url': '/media/sslc/math/ch11.pdf'},
        ],
        'english': [
            {'id': 1, 'name': 'A Very Old Man with Enormous Wings',
                'file_url': '/media/sslc/english/ch1.pdf'},
            {'id': 2, 'name': 'In THe Attic',
             'file_url': '/media/sslc/english/ch2.pdf'},
            {'id': 3, 'name': '"Friends,Romans,Countrymen..." ',
                'file_url': '/media/sslc/english/ch3.pdf'},
            {'id': 4, 'name': 'Breaking Barriers,I will Fly',
                'file_url': '/media/sslc/english/ch4.pdf'},
            {'id': 5, 'name': 'A Phoenix Rises',
                'file_url': '/media/sslc/english/ch5.pdf'},
            {'id': 6, 'name': 'The Seedling',
                'file_url': '/media/sslc/english/ch6.pdf'},
            {'id': 7, 'name': 'Another Day in Paradise',
                'file_url': '/media/sslc/english/ch7.pdf'},
            {'id': 8, 'name': 'War',
                'file_url': '/media/sslc/english/ch8.pdf'},
            {'id': 9, 'name': 'A Piece of String',
                'file_url': '/media/sslc/english/ch9.pdf'},
            {'id': 10, 'name': 'Shakuntalam',
                'file_url': '/media/sslc/english/ch10.pdf'},
            {'id': 11, 'name': 'Trills and Thrills:Birdwtching in India',
                'file_url': '/media/sslc/english/ch11.pdf'},
            {'id': 12, 'name': 'The Wild Swans at Coole',
                'file_url': '/media/sslc/english/ch12.pdf'},
            {'id': 13, 'name': 'Beloved Boles',
                'file_url': '/media/sslc/english/ch13.pdf'},
            {'id': 14, 'name': 'Preference Nationale',
                'file_url': '/media/sslc/english/ch14.pdf'},
        ],
        'geography': [
            {'id': 1, 'name': 'Weather and Climate',
                'file_url': '/media/sslc/geography/ch1.pdf'},
            {'id': 2, 'name': 'Climatic Regions and Climate Change',
                'file_url': '/media/sslc/geography/ch2.pdf'},
            {'id': 3, 'name': 'From the Rainy Forests to The Land of Permafrost',
                'file_url': '/media/sslc/geography/ch3.pdf'},
            {'id': 4, 'name': 'Consumer: Rights and Protection',
                'file_url': '/media/sslc/geography/ch4.pdf'},
            {'id': 5, 'name': 'Money and Economy',
                'file_url': '/media/sslc/geography/ch5.pdf'},
            {'id': 6, 'name': 'The Changing of Earth',
                'file_url': '/media/sslc/geography/ch6.pdf'},
            {'id': 7, 'name': 'Indian Economy : Growth and Transformation',
                'file_url': '/media/sslc/geography/ch7.pdf'},
            {'id': 8, 'name': 'Towards Sustainability',
                'file_url': '/media/sslc/geography/ch8.pdf'},

        ],
        'history': [
            {'id': 1, 'name': 'Humanism',
                'file_url': '/media/sslc/history/ch1.pdf'},
            {'id': 2, 'name': 'Liberty Equality Fratility',
                'file_url': '/media/sslc/history/ch2.pdf'},
            {'id': 3, 'name': 'Social Analysis: Through Sociological Imaghination',
                'file_url': '/media/sslc/history/ch3.pdf'},
            {'id': 4, 'name': 'Wealth and the World',
                'file_url': '/media/sslc/history/ch4.pdf'},
            {'id': 5, 'name': 'Public Opinion in Democracy',
                'file_url': '/media/sslc/history/ch5.pdf'},
            {'id': 6, 'name': 'Mass Movement For Freedom',
                'file_url': '/media/sslc/history/ch6.pdf'},
            {'id': 7, 'name': 'The Glipmse of Free India',
                'file_url': '/media/sslc/history/ch7.pdf'},
            {'id': 8, 'name': 'Democracy an Indian Experience',
                'file_url': '/media/sslc/history/ch8.pdf'},
            {'id': 9, 'name': 'Know The Indian social System',
                'file_url': '/media/sslc/history/ch9.pdf'},
        ],


    },
    'plus-one': {


        'physics': [
            {'id': 1, 'name': 'Units and Measurements',
                'file_url': '/media/p1/phy/ch1.pdf'},
            {'id': 2, 'name': 'Motion in a Straight Line',
                'file_url': '/media/p1/phy/ch2.pdf'},
            {'id': 3, 'name': 'Motion in a Plane',
                'file_url': '/media/p1/phy/ch3.pdf'},
            {'id': 4, 'name': 'Laws of Motion',
                'file_url': '/media/p1/phy/ch4.pdf'},
            {'id': 5, 'name': 'Work, Energy and Power',
                'file_url': '/media/p1/phy/ch5.pdf'},
            {'id': 6, 'name': 'System of Particles and Rotational Motion',
                'file_url': '/media/p1/phy/ch6.pdf'},
            {'id': 7, 'name': 'Gravitation',
                'file_url': '/media/p1/phy/ch7.pdf'},
            {'id': 8, 'name': 'Mechanical Properties of Solids',
                'file_url': '/media/p1/phy/ch8.pdf'},
            {'id': 9, 'name': 'Mechanical Properties of Fluids',
                'file_url': '/media/p1/phy/ch9.pdf'},
            {'id': 10, 'name': 'Thermal Properties of Matter',
                'file_url': '/media/p1/phy/ch10.pdf'},
            {'id': 11, 'name': 'Thermodynamics',
                'file_url': '/media/p1/phy/ch11.pdf'},
            {'id': 12, 'name': 'Kinetic Theory',
                'file_url': '/media/p1/phy/ch12.pdf'},
            {'id': 13, 'name': 'Oscillations',
                'file_url': '/media/p1/phy/ch13.pdf'},
            {'id': 14, 'name': 'Waves',
                'file_url': '/media/p1/phy/ch14.pdf'},
        ],
        'mathematics': [
            {'id': 1, 'name': 'Sets', 'file_url': '/media/p1/math/ch1.pdf'},
            {'id': 2, 'name': 'Relations and Functions',
                'file_url': '/media/p1/math/ch2.pdf'},
            {'id': 3, 'name': 'Trigonometric Functions',
                'file_url': '/media/p1/math/ch3.pdf'},
            {'id': 4, 'name': 'Complex Numbers',
                'file_url': '/media/p1/math/ch4.pdf'},
            {'id': 5, 'name': 'Linear Inequalities',
                'file_url': '/media/p1/math/ch5.pdf'},
            {'id': 6, 'name': 'Permutations and Combinations',
                'file_url': '/media/p1/math/ch6.pdf'},
            {'id': 7, 'name': 'Binomial Theorem',
                'file_url': '/media/p1/math/ch7.pdf'},
            {'id': 8, 'name': 'Sequence and Series',
                'file_url': '/media/p1/math/ch8.pdf'},
            {'id': 9, 'name': 'Straight Lines',
                'file_url': '/media/p1/math/ch9.pdf'},
            {'id': 10, 'name': 'Conic Sections',
                'file_url': '/media/p1/math/ch10.pdf'},
            {'id': 11, 'name': 'Introduction to Three Dimensional Geometry',
                'file_url': '/media/p1/math/ch11.pdf'},
            {'id': 12, 'name': 'Limits and Derivatives',
                'file_url': '/media/p1/math/ch12.pdf'},
            {'id': 13, 'name': 'Statistics',
                'file_url': '/media/p1/math/ch13.pdf'},
            {'id': 14, 'name': 'Probability',
                'file_url': '/media/p1/math/ch14.pdf'},
        ],
        'chemistry': [
            {'id': 1, 'name': 'Some Basic Concepts of Chemistry',
                'file_url': '/media/p1/chem/ch1.pdf'},
            {'id': 2, 'name': 'Structure of Atom',
                'file_url': '/media/p1/chem/ch2.pdf'},
            {'id': 3, 'name': 'Classification of Elements and Periodicity in Properties',
                'file_url': '/media/p1/chem/ch3.pdf'},
            {'id': 4, 'name': 'Chemical Bonding and Molecular Structure',
                'file_url': '/media/p1/chem/ch4.pdf'},
            {'id': 5, 'name': 'Thermodynamics',
                'file_url': '/media/p1/chem/ch5.pdf'},
            {'id': 6, 'name': 'Equilibrium',
                'file_url': '/media/p1/chem/ch6.pdf'},
            {'id': 7, 'name': 'Redox Reactions',
                'file_url': '/media/p1/chem/ch7.pdf'},
            {'id': 8, 'name': 'Organic Chemistry: Basic Principles',
                'file_url': '/media/p1/chem/ch8.pdf'},
            {'id': 9, 'name': 'Hydrocarbons',
                'file_url': '/media/p1/chem/ch9.pdf'},

        ],
        'botany': [
            {'id': 1, 'name': 'Biological Classification',
                'file_url': '/media/p1/bot/ch1.pdf'},
            {'id': 2, 'name': 'Plant Kingdom',
                'file_url': '/media/p1/bot/ch2.pdf'},
            {'id': 3, 'name': 'Morphology of Flowering Plants',
                'file_url': '/media/p1/bot/ch3.pdf'},
            {'id': 4, 'name': 'Anatomy of Flowering Plants',
                'file_url': '/media/p1/bot/ch4.pdf'},
            {'id': 5, 'name': 'Cell: The Unit of Life',
                'file_url': '/media/p1/bot/ch5.pdf'},
            {'id': 6, 'name': 'Cell Cycle and Cell Division',
                'file_url': '/media/p1/bot/ch6.pdf'},
            {'id': 7, 'name': 'Photosynthesis in Higher Plants',
                'file_url': '/media/p1/bot/ch7.pdf'},
            {'id': 8, 'name': 'Respiration in Plants',
                'file_url': '/media/p1/bot/ch8.pdf'},
            {'id': 9, 'name': 'Plant Growth and Development',
                'file_url': '/media/p1/bot/ch9.pdf'},

        ],
        'zoology': [
            {'id': 1, 'name': 'The Living World"',
                'file_url': '/media/p1/zoo/ch1.pdf'},
            {'id': 2, 'name': 'Animal Kingdom',
                'file_url': '/media/p1/zoo/ch2.pdf'},
            {'id': 3, 'name': 'Structural Organisation in Animals',
                'file_url': '/media/p1/zoo/ch3.pdf'},
            {'id': 4, 'name': 'Biomolecules',
                'file_url': '/media/p1/zoo/ch4.pdf'},
            {'id': 5, 'name': 'Breathing and Exchange of Gases',
                'file_url': '/media/p1/zoo/ch5.pdf'},
            {'id': 6, 'name': 'Body Fluids and Circulation',
                'file_url': '/media/p1/zoo/ch6.pdf'},
            {'id': 7, 'name': 'Excretory Products and their Elimination',
                'file_url': '/media/p1/zoo/ch7.pdf'},
            {'id': 8, 'name': 'Locomotion and Movement',
                'file_url': '/media/p1/zoo/ch8.pdf'},
            {'id': 9, 'name': 'Neural Control and Coordination',
                'file_url': '/media/p1/zoo/ch9.pdf'},
            {'id': 10, 'name': 'Chemical Coordination and Integration',
                'file_url': '/media/p1/zoo/ch10.pdf'},
        ],
        'computer-science': [
            {'id': 1, 'name': 'Data Representation',
                'file_url': '/media/p1/cs/ch1.pdf'},
            {'id': 2, 'name': 'Fundamentals of Computer',
                'file_url': '/media/p1/cs/ch2.pdf'},
            {'id': 3, 'name': 'Computer Software',
                'file_url': '/media/p1/cs/ch3.pdf'},
            {'id': 4, 'name': 'Introduction to Programming',
                'file_url': '/media/p1/cs/ch4.pdf'},
            {'id': 5, 'name': 'Getting Started with C++',
                'file_url': '/media/p1/cs/ch5.pdf'},
            {'id': 6, 'name': 'Operators and Expressions',
                'file_url': '/media/p1/cs/ch6.pdf'},
            {'id': 7, 'name': 'Control Statements',
                'file_url': '/media/p1/cs/ch7.pdf'},
            {'id': 8, 'name': 'Arrays',
                'file_url': '/media/p1/cs/ch8.pdf'},
            {'id': 9, 'name': 'String Handling and Functions',
                'file_url': '/media/p1/cs/ch9.pdf'},
            {'id': 10, 'name': 'IT and Society',
                'file_url': '/media/p1/cs/ch10.pdf'},
        ],
        'computer-app': [
            {'id': 1, 'name': 'Fundamentals of Computer',
                'file_url': '/media/p1/ca/ch1.pdf'},
            {'id': 2, 'name': 'Components of Computer System',
                'file_url': '/media/p1/ca/ch2.pdf'},
            {'id': 3, 'name': 'Principles of Programming',
                'file_url': '/media/p1/ca/ch3.pdf'},
            {'id': 4, 'name': 'Getting Started with C++',
                'file_url': '/media/p1/ca/ch4.pdf'},
            {'id': 5, 'name': 'Data Types and Operators',
                'file_url': '/media/p1/ca/ch5.pdf'},
            {'id': 6, 'name': 'Introduction to Programming',
                'file_url': '/media/p1/ca/ch6.pdf'},
            {'id': 7, 'name': 'Control Statements',
                'file_url': '/media/p1/ca/ch7.pdf'},
            {'id': 8, 'name': 'Computer Networks',
                'file_url': '/media/p1/ca/ch8.pdf'},
            {'id': 9, 'name': 'Internet',
                'file_url': '/media/p1/ca/ch9.pdf'},
            {'id': 10, 'name': 'IT Applications',
                'file_url': '/media/p1/ca/ch10.pdf'},
        ],
        'english': [
            {'id': 1, 'name': 'His First Flight',
                'file_url': '/media/p1/english/ch1.pdf'},
            {'id': 2, 'name': 'I Will Fly (Speech)',
                'file_url': '/media/p1/english/ch2.pdf'},
            {'id': 3, 'name': 'Quest for a Theory of Everything',
                'file_url': '/media/p1/english/ch3.pdf'},
            {'id': 4, 'name': 'If (Poem)',
                'file_url': '/media/p1/english/ch4.pdf'},
            {'id': 5, 'name': 'The Serang of Ranaganji',
                'file_url': '/media/p1/english/ch5.pdf'},
            {'id': 6, 'name': 'The Wreck of the Titanic (Poem)',
                'file_url': '/media/p1/english/ch6.pdf'},
            {'id': 7, 'name': 'Gooseberries',
                'file_url': '/media/p1/english/ch7.pdf'},
            {'id': 8, 'name': 'Death the Leveller (Poem)',
                'file_url': '/media/p1/english/ch8.pdf'},
            {'id': 9, 'name': 'Sunrise on the Hills (Poem)',
                'file_url': '/media/p1/english/ch9.pdf'},
            {'id': 10, 'name': 'The Trip of Le Horla',
                'file_url': '/media/p1/english/ch10.pdf'},
            {'id': 11, 'name': 'The Sacred Turtles of Kadavu',
                'file_url': '/media/p1/english/ch11.pdf'},
            {'id': 12, 'name': 'Disasters and Disaster Management',
                'file_url': '/media/p1/english/ch12.pdf'},
            {'id': 13, 'name': 'The Song of the Flower (Poem)',
                'file_url': '/media/p1/english/ch13.pdf'},
            {'id': 14, 'name': 'The Merchant of Venice (Drama)',
                'file_url': '/media/p1/english/ch14.pdf'},
            {'id': 15, 'name': 'The Cyberspace',
                'file_url': '/media/p1/english/ch15.pdf'},
            {'id': 16, 'name': 'Is Society Dead?',
                'file_url': '/media/p1/english/ch16.pdf'},
            {'id': 17, 'name': 'Conceptual Fruit',
                'file_url': '/media/p1/english/ch17.pdf'},
        ],
        'accountancy': [
            {'id': 1, 'name': 'Introduction to Accounting',
                'file_url': '/media/p1/acc/ch1.pdf'},
            {'id': 2, 'name': 'Theory Base of Accounting',
                'file_url': '/media/p1/acc/ch2.pdf'},
            {'id': 3, 'name': 'Recording of Transactions – I',
                'file_url': '/media/p1/acc/ch3.pdf'},
            {'id': 4, 'name': 'Recording of Transactions – II',
                'file_url': '/media/p1/acc/ch4.pdf'},
            {'id': 5, 'name': 'Bank Reconciliation Statement',
                'file_url': '/media/p1/acc/ch5.pdf'},
            {'id': 6, 'name': 'Trial Balance and Rectification of Errors',
                'file_url': '/media/p1/acc/ch6.pdf'},
            {'id': 7, 'name': 'Depreciation, Provisions and Reserves',
                'file_url': '/media/p1/acc/ch7.pdf'},
            {'id': 8, 'name': 'Bills of Exchange',
                'file_url': '/media/p1/acc/ch8.pdf'},
            {'id': 9, 'name': 'Financial Statements – I',
                'file_url': '/media/p1/acc/ch9.pdf'},
            {'id': 10, 'name': 'Financial Statements – II',
                'file_url': '/media/p1/acc/ch10.pdf'},
            {'id': 11, 'name': 'Accounts from Incomplete Records',
                'file_url': '/media/p1/acc/ch11.pdf'},
            {'id': 12, 'name': 'Applications of Computers in Accounting',
                'file_url': '/media/p1/acc/ch12.pdf'},
            {'id': 13, 'name': 'Computerised Accounting System',
                'file_url': '/media/p1/acc/ch13.pdf'},
        ],
        'business_studies': [
            {'id': 1, 'name': 'Business, Trade and Commerce',
                'file_url': '/media/p1/bs/ch1.pdf'},
            {'id': 2, 'name': 'Forms of Business Organisation',
                'file_url': '/media/p1/bs/ch2.pdf'},
            {'id': 3, 'name': 'Private, Public and Global Enterprises',
                'file_url': '/media/p1/bs/ch3.pdf'},
            {'id': 4, 'name': 'Business Services',
                'file_url': '/media/p1/bs/ch4.pdf'},
            {'id': 5, 'name': 'Emerging Modes of Business',
                'file_url': '/media/p1/bs/ch5.pdf'},
            {'id': 6, 'name': 'Social Responsibilities of Business and Business Ethics',
                'file_url': '/media/p1/bs/ch6.pdf'},
            {'id': 7, 'name': 'Formation of a Company',
                'file_url': '/media/p1/bs/ch7.pdf'},
            {'id': 8, 'name': 'Sources of Business Finance',
                'file_url': '/media/p1/bs/ch8.pdf'},
            {'id': 9, 'name': 'Small Business and Entrepreneurship',
                'file_url': '/media/p1/bs/ch9.pdf'},
            {'id': 10, 'name': 'Internal Trade',
                'file_url': '/media/p1/bs/ch10.pdf'},
            {'id': 11, 'name': 'International Business',
                'file_url': '/media/p1/bs/ch11.pdf'},
        ],
        'economics': [
            # Part 1: Statistics for Economics
            {'id': 1, 'name': 'Introduction to Statistics',
                'file_url': '/media/p1/eco/ch1.pdf'},
            {'id': 2, 'name': 'Collection of Data',
                'file_url': '/media/p1/eco/ch2.pdf'},
            {'id': 3, 'name': 'Organisation of Data',
                'file_url': '/media/p1/eco/ch3.pdf'},
            {'id': 4, 'name': 'Presentation of Data',
                'file_url': '/media/p1/eco/ch4.pdf'},
            {'id': 5, 'name': 'Measures of Central Tendency',
                'file_url': '/media/p1/eco/ch5.pdf'},
            {'id': 6, 'name': 'Correlation', 'file_url': '/media/p1/eco/ch6.pdf'},
            {'id': 7, 'name': 'Index Numbers', 'file_url': '/media/p1/eco/ch7.pdf'},
            # Part 2: Indian Economic Development
            {'id': 8, 'name': 'Indian Economy on the Eve of Independence',
                'file_url': '/media/p1/eco/ch8.pdf'},
            {'id': 9, 'name': 'Indian Economy 1950-1990',
                'file_url': '/media/p1/eco/ch9.pdf'},
            {'id': 10, 'name': 'Liberalisation, Privatisation and Globalisation',
                'file_url': '/media/p1/eco/ch10.pdf'},
            {'id': 11, 'name': 'Human Capital Formation in India',
                'file_url': '/media/p1/eco/ch11.pdf'},
            {'id': 12, 'name': 'Rural Development',
                'file_url': '/media/p1/eco/ch12.pdf'},
            {'id': 13, 'name': 'Employment: Growth, Informalisation and Other Issues',
                'file_url': '/media/p1/eco/ch13.pdf'},
            {'id': 14, 'name': 'Environment and Sustainable Development',
                'file_url': '/media/p1/eco/ch14.pdf'},
            {'id': 15, 'name': 'Comparative Development Experiences of India and its Neighbours',
                'file_url': '/media/p1/eco/ch15.pdf'},
        ],


    },

    'plus-two': {
        'physics': [
            # Part 1: Electricity and Magnetism
            {'id': 1, 'name': 'Electric Charges and Fields',
                'file_url': '/media/p2/phy/ch1.pdf'},
            {'id': 2, 'name': 'Electrostatic Potential and Capacitance',
                'file_url': '/media/p2/phy/ch2.pdf'},
            {'id': 3, 'name': 'Current Electricity',
                'file_url': '/media/p2/phy/ch3.pdf'},
            {'id': 4, 'name': 'Moving Charges and Magnetism',
                'file_url': '/media/p2/phy/ch4.pdf'},
            {'id': 5, 'name': 'Magnetism and Matter',
                'file_url': '/media/p2/phy/ch5.pdf'},
            {'id': 6, 'name': 'Electromagnetic Induction',
                'file_url': '/media/p2/phy/ch6.pdf'},
            {'id': 7, 'name': 'Alternating Current',
                'file_url': '/media/p2/phy/ch7.pdf'},
            {'id': 8, 'name': 'Electromagnetic Waves',
                'file_url': '/media/p2/phy/ch8.pdf'},

            # Part 2: Optics and Modern Physics
            {'id': 9, 'name': 'Ray Optics and Optical Instruments',
                'file_url': '/media/p2/phy/ch9.pdf'},
            {'id': 10, 'name': 'Wave Optics', 'file_url': '/media/p2/phy/ch10.pdf'},
            {'id': 11, 'name': 'Dual Nature of Radiation and Matter',
                'file_url': '/media/p2/phy/ch11.pdf'},
            {'id': 12, 'name': 'Atoms', 'file_url': '/media/p2/phy/ch12.pdf'},
            {'id': 13, 'name': 'Nuclei', 'file_url': '/media/p2/phy/ch13.pdf'},
            {'id': 14, 'name': 'Semiconductor Electronics',
                'file_url': '/media/p2/phy/ch14.pdf'},
        ],
        'chemistry': [
            # Physical & Inorganic Chemistry
            {'id': 1, 'name': 'Solutions', 'file_url': '/media/p2/chem/ch1.pdf'},
            {'id': 2, 'name': 'Electrochemistry',
                'file_url': '/media/p2/chem/ch2.pdf'},
            {'id': 3, 'name': 'Chemical Kinetics',
                'file_url': '/media/p2/chem/ch3.pdf'},
            {'id': 4, 'name': 'd- and f- Block Elements',
                'file_url': '/media/p2/chem/ch4.pdf'},
            {'id': 5, 'name': 'Coordination Compounds',
                'file_url': '/media/p2/chem/ch5.pdf'},

            # Organic Chemistry
            {'id': 6, 'name': 'Haloalkanes and Haloarenes',
                'file_url': '/media/p2/chem/ch6.pdf'},
            {'id': 7, 'name': 'Alcohols, Phenols and Ethers',
                'file_url': '/media/p2/chem/ch7.pdf'},
            {'id': 8, 'name': 'Aldehydes, Ketones and Carboxylic Acids',
                'file_url': '/media/p2/chem/ch8.pdf'},
            {'id': 9, 'name': 'Amines', 'file_url': '/media/p2/chem/ch9.pdf'},
            {'id': 10, 'name': 'Biomolecules',
                'file_url': '/media/p2/chem/ch10.pdf'},
        ],
        'accountancy': [
            # Part 1: Accounting for Partnership Firms
            {'id': 1, 'name': 'Accounting for Partnership: Basic Concepts',
                'file_url': '/media/p2/acc/ch1.pdf'},
            {'id': 2, 'name': 'Reconstitution of Partnership: Admission of a Partner',
                'file_url': '/media/p2/acc/ch2.pdf'},
            {'id': 3, 'name': 'Reconstitution of Partnership: Retirement/Death of a Partner',
                'file_url': '/media/p2/acc/ch3.pdf'},
            {'id': 4, 'name': 'Dissolution of Partnership Firm',
                'file_url': '/media/p2/acc/ch4.pdf'},

            # Part 2: Company Accounts and Analysis
            {'id': 5, 'name': 'Accounting for Share Capital',
                'file_url': '/media/p2/acc/ch5.pdf'},
            {'id': 6, 'name': 'Issue and Redemption of Debentures',
                'file_url': '/media/p2/acc/ch6.pdf'},
            {'id': 7, 'name': 'Financial Statements of a Company',
                'file_url': '/media/p2/acc/ch7.pdf'},
            {'id': 8, 'name': 'Analysis of Financial Statements',
                'file_url': '/media/p2/acc/ch8.pdf'},
            {'id': 9, 'name': 'Accounting Ratios',
                'file_url': '/media/p2/acc/ch9.pdf'},
            {'id': 10, 'name': 'Cash Flow Statement',
                'file_url': '/media/p2/acc/ch10.pdf'},
        ],
        'computer-science': [
            {'id': 1, 'name': 'Structures and Pointers',
                'file_url': '/media/p2/cs/ch1.pdf'},
            {'id': 2, 'name': 'Concepts of Object-Oriented Programming',
                'file_url': '/media/p2/cs/ch2.pdf'},
            {'id': 3, 'name': 'Data Structures and Operations',
                'file_url': '/media/p2/cs/ch3.pdf'},
            {'id': 4, 'name': 'Web Technology', 'file_url': '/media/p2/cs/ch4.pdf'},
            {'id': 5, 'name': 'Web Designing using HTML',
                'file_url': '/media/p2/cs/ch5.pdf'},
            {'id': 6, 'name': 'Client Side Scripting using JavaScript',
                'file_url': '/media/p2/cs/ch6.pdf'},
            {'id': 7, 'name': 'Web Hosting', 'file_url': '/media/p2/cs/ch7.pdf'},
            {'id': 8, 'name': 'Database Management System',
                'file_url': '/media/p2/cs/ch8.pdf'},
            {'id': 9,
                'name': 'Structured Query Language (SQL)', 'file_url': '/media/p2/cs/ch9.pdf'},
            {'id': 10, 'name': 'Server Side Scripting using PHP',
                'file_url': '/media/p2/cs/ch10.pdf'},
            {'id': 11, 'name': 'Advances in Computing',
                'file_url': '/media/p2/cs/ch11.pdf'},
            {'id': 12, 'name': 'ICT and Society',
                'file_url': '/media/p2/cs/ch12.pdf'},
        ],
        'mathematics': [
            # Part 1: Relations, Algebra, and Calculus I
            {'id': 1, 'name': 'Relations and Functions',
                'file_url': '/media/p2/maths/ch1.pdf'},
            {'id': 2, 'name': 'Inverse Trigonometric Functions',
                'file_url': '/media/p2/maths/ch2.pdf'},
            {'id': 3, 'name': 'Matrices', 'file_url': '/media/p2/maths/ch3.pdf'},
            {'id': 4, 'name': 'Determinants', 'file_url': '/media/p2/maths/ch4.pdf'},
            {'id': 5, 'name': 'Continuity and Differentiability',
                'file_url': '/media/p2/maths/ch5.pdf'},
            {'id': 6, 'name': 'Application of Derivatives',
                'file_url': '/media/p2/maths/ch6.pdf'},

            # Part 2: Calculus II, Vectors, and Probability
            {'id': 7, 'name': 'Integrals', 'file_url': '/media/p2/maths/ch7.pdf'},
            {'id': 8, 'name': 'Application of Integrals',
                'file_url': '/media/p2/maths/ch8.pdf'},
            {'id': 9, 'name': 'Differential Equations',
                'file_url': '/media/p2/maths/ch9.pdf'},
            {'id': 10, 'name': 'Vector Algebra',
                'file_url': '/media/p2/maths/ch10.pdf'},
            {'id': 11, 'name': 'Three Dimensional Geometry',
                'file_url': '/media/p2/maths/ch11.pdf'},
            {'id': 12, 'name': 'Linear Programming',
                'file_url': '/media/p2/maths/ch12.pdf'},
            {'id': 13, 'name': 'Probability',
                'file_url': '/media/p2/maths/ch13.pdf'},
        ],
        'botany': [
            {'id': 1, 'name': 'Reproduction in Organisms',
                'file_url': '/media/p2/bot/ch1.pdf'},
            {'id': 2, 'name': 'Sexual Reproduction in Flowering Plants',
                'file_url': '/media/p2/bot/ch2.pdf'},
            {'id': 3, 'name': 'Strategies for Enhancement in Food Production',
                'file_url': '/media/p2/bot/ch3.pdf'},
            {'id': 4, 'name': 'Biotechnology: Principles and Processes',
                'file_url': '/media/p2/bot/ch4.pdf'},
            {'id': 5, 'name': 'Biotechnology and its Applications',
                'file_url': '/media/p2/bot/ch5.pdf'},
            {'id': 6, 'name': 'Organisms and Populations',
                'file_url': '/media/p2/bot/ch6.pdf'},
            {'id': 7, 'name': 'Ecosystem', 'file_url': '/media/p2/bot/ch7.pdf'},
            {'id': 8, 'name': 'Environmental Issues',
                'file_url': '/media/p2/bot/ch8.pdf'},
        ],
        'zoology': [
            {'id': 1, 'name': 'Human Reproduction',
                'file_url': '/media/p2/zoo/ch1.pdf'},
            {'id': 2, 'name': 'Reproductive Health',
                'file_url': '/media/p2/zoo/ch2.pdf'},
            {'id': 3, 'name': 'Principles of Inheritance and Variation',
                'file_url': '/media/p2/zoo/ch3.pdf'},
            {'id': 4, 'name': 'Molecular Basis of Inheritance',
                'file_url': '/media/p2/zoo/ch4.pdf'},
            {'id': 5, 'name': 'Evolution',
                'file_url': '/media/p2/zoo/ch5.pdf'},
            {'id': 6, 'name': 'Human Health and Disease',
                'file_url': '/media/p2/zoo/ch6.pdf'},
            {'id': 7, 'name': 'Microbes in Human Welfare',
                'file_url': '/media/p2/zoo/ch7.pdf'},
            {'id': 8, 'name': 'Organisms and Populations',
                'file_url': '/media/p2/zoo/ch8.pdf'},
        ],
        'english': [
            # Unit 1: Flights of Freedom
            {'id': 1, 'name': 'The 3Ls of Empowerment (Speech)',
             'file_url': '/media/p2/english/ch1.pdf'},
            {'id': 2, 'name': 'Any Woman (Poem)',
             'file_url': '/media/p2/english/ch2.pdf'},
            {'id': 3, 'name': 'Matchbox (Short Story)',
             'file_url': '/media/p2/english/ch3.pdf'},
            {'id': 4, 'name': 'Horegallu (Anecdote)',
             'file_url': '/media/p2/english/ch4.pdf'},

            # Unit 2: Heights of Harmony
            {'id': 5, 'name': 'Mending Wall (Poem)',
             'file_url': '/media/p2/english/ch5.pdf'},
            {'id': 6, 'name': 'Amigo Brothers (Short Story)',
             'file_url': '/media/p2/english/ch6.pdf'},
            {'id': 7, 'name': 'The Hour of Truth (One-act Play)',
             'file_url': '/media/p2/english/ch7.pdf'},

            # Unit 3: Challenges of Triumphs
            {'id': 8, 'name': 'A Three-Wheeled Revolution',
                'file_url': '/media/p2/english/ch8.pdf'},
            {'id': 9, 'name': 'Didi (Life Sketch)',
             'file_url': '/media/p2/english/ch9.pdf'},
            {'id': 10, 'name': 'Stammer (Poem)',
             'file_url': '/media/p2/english/ch10.pdf'},

            # Unit 4: Live and Let Live
            {'id': 11, 'name': 'When a Sapling is Planted',
                'file_url': '/media/p2/english/ch11.pdf'},
            {'id': 12, 'name': 'Rice (Poem)',
             'file_url': '/media/p2/english/ch12.pdf'},
            {'id': 13, 'name': 'Danger of a Single Story',
                'file_url': '/media/p2/english/ch13.pdf'},

            # Unit 5: The Cyber World
            {'id': 14, 'name': 'Post Early for Space (Poem)',
             'file_url': '/media/p2/english/ch14.pdf'},
            {'id': 15, 'name': 'This is Going to Hurt Just a Little Bit',
                'file_url': '/media/p2/english/ch15.pdf'},
            {'id': 16, 'name': 'Crime and Punishment (Short Story)',
             'file_url': '/media/p2/english/ch16.pdf'},
        ],
        'computer-application': [
            {'id': 1, 'name': 'Review of C++ Programming',
                'file_url': '/media/p2/ca/ch1.pdf'},
            {'id': 2, 'name': 'Arrays',
                'file_url': '/media/p2/ca/ch2.pdf'},
            {'id': 3, 'name': 'Functions',
                'file_url': '/media/p2/ca/ch3.pdf'},
            {'id': 4, 'name': 'Web Technology',
                'file_url': '/media/p2/ca/ch4.pdf'},
            {'id': 5, 'name': 'Web Designing using HTML',
                'file_url': '/media/p2/ca/ch5.pdf'},
            {'id': 6, 'name': 'Client Side Scripting using JavaScript',
                'file_url': '/media/p2/ca/ch6.pdf'},
            {'id': 7, 'name': 'Web Hosting',
                'file_url': '/media/p2/ca/ch7.pdf'},
            {'id': 8, 'name': 'Database Management System',
                'file_url': '/media/p2/ca/ch8.pdf'},
            {'id': 9, 'name': 'Structured Query Language (SQL)',
                'file_url': '/media/p2/ca/ch9.pdf'},
            {'id': 10, 'name': 'Enterprise Resource Planning (ERP)',
                'file_url': '/media/p2/ca/ch10.pdf'},
            {'id': 11, 'name': 'Trends and Issues in ICT',
                'file_url': '/media/p2/ca/ch11.pdf'},
        ],
        'business-studies': [
            # Part 1: Principles and Functions of Management
            {'id': 1, 'name': 'Nature and Significance of Management',
                'file_url': '/media/p2/bs/ch1.pdf'},
            {'id': 2, 'name': 'Principles of Management',
                'file_url': '/media/p2/bs/ch2.pdf'},
            {'id': 3, 'name': 'Business Environment',
                'file_url': '/media/p2/bs/ch3.pdf'},
            {'id': 4, 'name': 'Planning',
                'file_url': '/media/p2/bs/ch4.pdf'},
            {'id': 5, 'name': 'Organising',
                'file_url': '/media/p2/bs/ch5.pdf'},
            {'id': 6, 'name': 'Staffing',
                'file_url': '/media/p2/bs/ch6.pdf'},
            {'id': 7, 'name': 'Directing',
                'file_url': '/media/p2/bs/ch7.pdf'},
            {'id': 8, 'name': 'Controlling',
                'file_url': '/media/p2/bs/ch8.pdf'},

            # Part 2: Business Finance and Marketing
            {'id': 9, 'name': 'Financial Management',
                'file_url': '/media/p2/bs/ch9.pdf'},
            {'id': 10, 'name': 'Financial Markets',
                'file_url': '/media/p2/bs/ch10.pdf'},
            {'id': 11, 'name': 'Marketing Management',
                'file_url': '/media/p2/bs/ch11.pdf'},
            {'id': 12, 'name': 'Consumer Protection',
                'file_url': '/media/p2/bs/ch12.pdf'},
        ],
        'economics': [
            # Part 1: Introductory Microeconomics
            {'id': 1, 'name': 'Introduction to Microeconomics',
                'file_url': '/media/p2/eco/ch1.pdf'},
            {'id': 2, 'name': 'Theory of Consumer Behaviour',
                'file_url': '/media/p2/eco/ch2.pdf'},
            {'id': 3, 'name': 'Production and Costs',
                'file_url': '/media/p2/eco/ch3.pdf'},
            {'id': 4, 'name': 'The Theory of the Firm under Perfect Competition',
                'file_url': '/media/p2/eco/ch4.pdf'},
            {'id': 5, 'name': 'Market Equilibrium',
                'file_url': '/media/p2/eco/ch5.pdf'},

            # Part 2: Introductory Macroeconomics
            {'id': 6, 'name': 'Introduction to Macroeconomics',
                'file_url': '/media/p2/eco/ch6.pdf'},
            {'id': 7, 'name': 'National Income Accounting',
                'file_url': '/media/p2/eco/ch7.pdf'},
            {'id': 8, 'name': 'Money and Banking',
                'file_url': '/media/p2/eco/ch8.pdf'},
            {'id': 9, 'name': 'Determination of Income and Employment',
                'file_url': '/media/p2/eco/ch9.pdf'},
            {'id': 10, 'name': 'Government Budget and the Economy',
                'file_url': '/media/p2/eco/ch10.pdf'},
            {'id': 11, 'name': 'Open Economy Macroeconomics',
                'file_url': '/media/p2/eco/ch11.pdf'},
        ]

    }
}
